import * as React from "react";
import * as Types from "./types";

declare function CaptionHero(props: {
  as?: React.ElementType;
  caption?: Types.Visibility.VisibilityConditions;
  isVideo?: Types.Visibility.VisibilityConditions;
  isOffer?: Types.Visibility.VisibilityConditions;
  isList?: Types.Visibility.VisibilityConditions;
  titleSrc?: React.ReactNode;
  titleSz?: Types.Builtin.Text;
  titleLc?: Types.Builtin.Text;
  subtxt?: Types.Visibility.VisibilityConditions;
  subtxtSrc?: React.ReactNode;
  atrb?: Types.Visibility.VisibilityConditions;
  atrbAvtrSz?: Types.Builtin.Text;
  atrbAvtrShape?: Types.Builtin.Text;
  atrbAvtr2?: Types.Visibility.VisibilityConditions;
  atrbAvtr3?: Types.Visibility.VisibilityConditions;
  atrbAvtr4?: Types.Visibility.VisibilityConditions;
  atrbAvtr5?: Types.Visibility.VisibilityConditions;
  atrbAvtrSrc?: Types.Asset.Image;
  atrbAvtrAlt?: Types.Basic.AltText;
  atrbAvtr2Src?: Types.Asset.Image;
  atrbAvtr2Alt?: Types.Basic.AltText;
  atrbAvtr3Src?: Types.Asset.Image;
  atrbAvtr3Alt?: Types.Basic.AltText;
  atrbAvtr4Src?: Types.Asset.Image;
  atrbAvtr4Alt?: Types.Basic.AltText;
  atrbAvtr5Src?: Types.Asset.Image;
  atrbAvtr5Alt?: Types.Basic.AltText;
  atrbTime?: Types.Visibility.VisibilityConditions;
  atrbTimeSrc?: React.ReactNode;
  atrbName?: Types.Visibility.VisibilityConditions;
  atrbNameSrc?: React.ReactNode;
  atrbBdg?: Types.Visibility.VisibilityConditions;
  atrbBdg1?: Types.Visibility.VisibilityConditions;
  atrbBdg1Icn?: Types.Visibility.VisibilityConditions;
  atrbBdg1TxtSrc?: React.ReactNode;
  atrbBdg1IcnSrc?: React.ReactNode;
  atrbClick?: Types.Devlink.RuntimeProps;
  captDetClick?: Types.Devlink.RuntimeProps;
  atrbActClick?: Types.Devlink.RuntimeProps;
  pBtmBrdr?: Types.Builtin.Text;
  tBtmBrdr?: Types.Builtin.Text;
}): React.JSX.Element;
