import * as React from "react";
import * as Types from "./types";

declare function CardPeepData(props: {
  as?: React.ElementType;
  card?: Types.Visibility.VisibilityConditions;
  cardId?: Types.Basic.IdTextInput;
  peep?: Types.Visibility.VisibilityConditions;
  group?: Types.Visibility.VisibilityConditions;
  avtrSrc?: Types.Asset.Image;
  avtrAlt?: Types.Basic.AltText;
  avtrBdgClr?: Types.Builtin.Text;
  titleSrc?: React.ReactNode;
  profLink?: Types.Basic.Link;
  profClick?: Types.Devlink.RuntimeProps;
  chatLink?: Types.Basic.Link;
  chatBtnClick?: Types.Devlink.RuntimeProps;
  moreLink?: Types.Basic.Link;
  moreBtnClick?: Types.Devlink.RuntimeProps;
  listQty?: React.ReactNode;
  lsAdpt1IcnSrc?: React.ReactNode;
  lsAdpt1BgClr?: Types.Builtin.Text;
  lsAdpt2BgClr?: Types.Builtin.Text;
  lsAdpt2CnSrc?: React.ReactNode;
  lsAdpt3BgClr?: Types.Builtin.Text;
  lsAdpt3IcnSrc?: React.ReactNode;
  listLink?: Types.Basic.Link;
  listClick?: Types.Devlink.RuntimeProps;
  peepQty?: React.ReactNode;
  peepAvtr1Src?: Types.Asset.Image;
  peepAvtr2Src?: Types.Asset.Image;
  peepAvtr3Src?: Types.Asset.Image;
  peepLink?: Types.Basic.Link;
  peepClick?: Types.Devlink.RuntimeProps;
  calQty?: React.ReactNode;
  calAdpt1IcnSrc?: React.ReactNode;
  calAdpt1BgClr?: Types.Builtin.Text;
  calAdpt2BgClr?: Types.Builtin.Text;
  calAdpt2CnSrc?: React.ReactNode;
  calAdpt3BgClr?: Types.Builtin.Text;
  calAdpt3IcnSrc?: React.ReactNode;
  calLink?: Types.Basic.Link;
  calClick?: Types.Devlink.RuntimeProps;
}): React.JSX.Element;
