import * as React from "react";
import * as Types from "./types";

declare function CardGroupData(props: {
  as?: React.ElementType;
  card?: Types.Visibility.VisibilityConditions;
  cardId?: Types.Basic.IdTextInput;
  simple?: Types.Visibility.VisibilityConditions;
  cover?: Types.Visibility.VisibilityConditions;
  avtr2?: Types.Visibility.VisibilityConditions;
  avtr3?: Types.Visibility.VisibilityConditions;
  avtr4?: Types.Visibility.VisibilityConditions;
  avtr5?: Types.Visibility.VisibilityConditions;
  avtr1Src?: Types.Asset.Image;
  avtr2Src?: Types.Asset.Image;
  avtr3Src?: Types.Asset.Image;
  avtr4Src?: Types.Asset.Image;
  avtr5Src?: Types.Asset.Image;
  cvrImgSrc?: Types.Asset.Image;
  cvrAltSrc?: Types.Basic.AltText;
  titleSrc?: React.ReactNode;
  profClick?: Types.Devlink.RuntimeProps;
  chatBtnClick?: Types.Devlink.RuntimeProps;
  moreBtnClick?: Types.Devlink.RuntimeProps;
  exampleRoom?: Types.Visibility.VisibilityConditions;
  exampleGallery?: Types.Visibility.VisibilityConditions;
  roomMap?: Types.Devlink.Slot;
  galMap?: Types.Devlink.Slot;
  atchMap?: Types.Devlink.Slot;
  pplMap?: Types.Devlink.Slot;
  stats?: Types.Visibility.VisibilityConditions;
  stat2?: Types.Visibility.VisibilityConditions;
  stat3?: Types.Visibility.VisibilityConditions;
  stat4?: Types.Visibility.VisibilityConditions;
  stat1Src?: React.ReactNode;
  stat2Src?: React.ReactNode;
  stat3Src?: React.ReactNode;
  stat4Src?: React.ReactNode;
  exampleRmIcnSrc?: React.ReactNode;
  exampleRmNameSrc?: React.ReactNode;
  exampleRmClick?: Types.Devlink.RuntimeProps;
  exampleGalImgSrc?: Types.Asset.Image;
  exampleGalImgAlt?: Types.Basic.AltText;
  exampleGalNameSrc?: React.ReactNode;
  exampleGalClick?: Types.Devlink.RuntimeProps;
}): React.JSX.Element;
