import * as React from "react";
import * as Types from "./types";

declare function CellProdFeat(props: {
  as?: React.ElementType;
  cell?: Types.Visibility.VisibilityConditions;
  vizSrc?: Types.Asset.Image;
  vizAlt?: Types.Basic.AltText;
  vizSz?: Types.Builtin.Text;
  capt?: Types.Visibility.VisibilityConditions;
  captTitleSrc?: React.ReactNode;
  captSubtxt?: Types.Visibility.VisibilityConditions;
  captSubtxtSrc?: React.ReactNode;
  amt?: React.ReactNode;
  amtHigh?: Types.Visibility.VisibilityConditions;
  amtH?: React.ReactNode;
  seller2?: Types.Visibility.VisibilityConditions;
  seller3?: Types.Visibility.VisibilityConditions;
  seller1Src?: Types.Asset.Image;
  seller2Src?: Types.Asset.Image;
  seller3Src?: Types.Asset.Image;
  cellSz?: Types.Builtin.Text;
  cellCard?: Types.Builtin.Text;
  cellClr?: Types.Builtin.Text;
  cellClick?: Types.Devlink.RuntimeProps;
  favBtn?: Types.Visibility.VisibilityConditions;
  listBtn?: Types.Visibility.VisibilityConditions;
  cartBtn?: Types.Visibility.VisibilityConditions;
  favIcnSrc?: React.ReactNode;
  favIcnClr?: Types.Builtin.Text;
  favBtnDis?: Types.Builtin.Text;
  favBtnClick?: Types.Devlink.RuntimeProps;
  listBtnDis?: Types.Builtin.Text;
  listBtnClick?: Types.Devlink.RuntimeProps;
  cartBtnDis?: Types.Builtin.Text;
  cartBtnClick?: Types.Devlink.RuntimeProps;
  cartStep?: Types.Visibility.VisibilityConditions;
  cartQty?: React.ReactNode;
  cartMoreClick?: Types.Devlink.RuntimeProps;
  cartLessClick?: Types.Devlink.RuntimeProps;
}): React.JSX.Element;
