"use client";
import React from "react";
import * as _Builtin from "./_Builtin";
import * as _utils from "./utils";
import _styles from "./GridGuide.module.css";

export function GridGuide({
  as: _Component = _Builtin.Block,
  visibility = true,
}) {
  return visibility ? (
    <_Component
      className={_utils.cx(_styles, "styleguide_guide_wrap")}
      tag="div"
    >
      <_Builtin.HtmlEmbed value="%3Cstyle%3E%0Ahtml%3Anot(.wf-design-mode)%20.styleguide_guide_wrap%20%7B%0A%09display%3A%20none%3B%0A%7D%0A.styleguide_guide_layout%20%7B%0A%09counter-reset%3A%20gridguides%3B%0A%7D%0A.styleguide_guide_layout%20%3E%20div%3A%3Abefore%20%7B%0A%20%20counter-increment%3A%20gridguides%3B%0A%20%20content%3A%20counter(gridguides)%3B%0A%7D%0A%3C%2Fstyle%3E" />
      <_Builtin.Block
        className={_utils.cx(
          _styles,
          "styleguide_guide_contain",
          "u-container"
        )}
        tag="div"
        data-padding-top="none"
        data-padding-bottom="none"
      >
        <_Builtin.Block
          className={_utils.cx(
            _styles,
            "styleguide_guide_layout",
            "u-grid-custom"
          )}
          tag="div"
        >
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
          <_Builtin.Block
            className={_utils.cx(
              _styles,
              "styleguide_guide_column",
              "u-vflex-center-bottom"
            )}
            tag="div"
          />
        </_Builtin.Block>
      </_Builtin.Block>
    </_Component>
  ) : null;
}
