import * as React from "react";
import * as Types from "./types";

declare function LicLead(props: {
  as?: React.ElementType;
  icn?: Types.Visibility.VisibilityConditions;
  img?: Types.Visibility.VisibilityConditions;
  avtr?: Types.Visibility.VisibilityConditions;
  adptIcn?: Types.Visibility.VisibilityConditions;
  rdio?: Types.Visibility.VisibilityConditions;
  icnSrc?: React.ReactNode;
  icnClr?: Types.Builtin.Text;
  icnSz?: Types.Builtin.Text;
  isSecHead?: Types.Builtin.Text;
  imgSrc?: Types.Asset.Image;
  imgAlt?: Types.Basic.AltText;
  imgSz?: Types.Builtin.Text;
  avtrSrc?: Types.Asset.Image;
  avtrAlt?: Types.Basic.AltText;
  avtrShape?: Types.Builtin.Text;
  avtrBdg?: Types.Visibility.VisibilityConditions;
  avtrBdgClr?: Types.Builtin.Text;
  avtrSz?: Types.Builtin.Text;
  avtrBdgSz?: Types.Builtin.Text;
  avtr2?: Types.Visibility.VisibilityConditions;
  avtr3?: Types.Visibility.VisibilityConditions;
  avtr4?: Types.Visibility.VisibilityConditions;
  avtr5?: Types.Visibility.VisibilityConditions;
  avtr2Src?: Types.Asset.Image;
  avtr2Alt?: Types.Basic.AltText;
  avtr3Src?: Types.Asset.Image;
  avtr3Alt?: Types.Basic.AltText;
  avtr4Src?: Types.Asset.Image;
  avtr4Alt?: Types.Basic.AltText;
  avtr5Src?: Types.Asset.Image;
  avtr5Alt?: Types.Basic.AltText;
  adptIcnSrc?: React.ReactNode;
  adptSz?: Types.Builtin.Text;
  adptBgClr?: Types.Builtin.Text;
  rdioIcn?: React.ReactNode;
  rdioClr?: Types.Builtin.Text;
  rdioSz?: Types.Builtin.Text;
  rdioClick?: Types.Devlink.RuntimeProps;
  leadDiv?: Types.Builtin.Text;
}): React.JSX.Element;
