import * as React from "react";
import * as Types from "./types";

declare function MenuGroup(props: {
  as?: React.ElementType;
  menu?: Types.Visibility.VisibilityConditions;
  mini?: Types.Builtin.Text;
  popId?: Types.Basic.IdTextInput;
  anchorId?: Types.Builtin.Text;
  report?: Types.Visibility.VisibilityConditions;
  feedback?: Types.Visibility.VisibilityConditions;
  remove?: Types.Visibility.VisibilityConditions;
  removeSrc?: React.ReactNode;
  removeG?: Types.Visibility.VisibilityConditions;
  leave?: Types.Visibility.VisibilityConditions;
  noInterest?: Types.Visibility.VisibilityConditions;
  block?: Types.Visibility.VisibilityConditions;
  mute?: Types.Visibility.VisibilityConditions;
  copyTxt?: Types.Visibility.VisibilityConditions;
  copyLink?: Types.Visibility.VisibilityConditions;
  share?: Types.Visibility.VisibilityConditions;
  feature?: Types.Visibility.VisibilityConditions;
  pin?: Types.Visibility.VisibilityConditions;
  alert?: Types.Visibility.VisibilityConditions;
  bkmrk?: Types.Visibility.VisibilityConditions;
  comment?: Types.Visibility.VisibilityConditions;
  search?: Types.Visibility.VisibilityConditions;
  edit?: Types.Visibility.VisibilityConditions;
  reportClick?: Types.Devlink.RuntimeProps;
  feedbackClick?: Types.Devlink.RuntimeProps;
  removeClick?: Types.Devlink.RuntimeProps;
  removeGClick?: Types.Devlink.RuntimeProps;
  leaveClick?: Types.Devlink.RuntimeProps;
  noInterestClick?: Types.Devlink.RuntimeProps;
  blockClick?: Types.Devlink.RuntimeProps;
  muteClick?: Types.Devlink.RuntimeProps;
  copyTxtClick?: Types.Devlink.RuntimeProps;
  copyLinkClick?: Types.Devlink.RuntimeProps;
  shareClick?: Types.Devlink.RuntimeProps;
  featureClick?: Types.Devlink.RuntimeProps;
  pinClick?: Types.Devlink.RuntimeProps;
  alertClick?: Types.Devlink.RuntimeProps;
  bkmrkClick?: Types.Devlink.RuntimeProps;
  commentClick?: Types.Devlink.RuntimeProps;
  searchClick?: Types.Devlink.RuntimeProps;
  editClick?: Types.Devlink.RuntimeProps;
}): React.JSX.Element;
