import * as React from "react";
import * as Types from "./types";

declare function MMemberList(props: {
  as?: React.ElementType;
  mbrList?: Types.Visibility.VisibilityConditions;
  itmGttrBdgPin?: Types.Visibility.VisibilityConditions;
  itmGttrBdgAlarm?: Types.Visibility.VisibilityConditions;
  itmGttrBdgBkmrk?: Types.Visibility.VisibilityConditions;
  moreClick?: Types.Devlink.RuntimeProps;
  anc?: Types.Visibility.VisibilityConditions;
  ancFetrExample?: Types.Visibility.VisibilityConditions;
  ancFetrAvtrSrc?: Types.Asset.Image;
  ancFetrAvtrAlt?: Types.Basic.AltText;
  ancFetrTitleSrc?: React.ReactNode;
  ancFetrSubtxtSrc?: React.ReactNode;
  ancFetrClick?: Types.Devlink.RuntimeProps;
  ancNewMap?: Types.Devlink.Slot;
  ancNewExample?: Types.Visibility.VisibilityConditions;
  ancNewAvtrSrc?: Types.Asset.Image;
  ancNewAvtrAlt?: Types.Basic.AltText;
  ancNewClick?: Types.Devlink.RuntimeProps;
  ancFetrStat1Src?: React.ReactNode;
  ancFetrStat2Src?: React.ReactNode;
  mbrAddClick?: Types.Devlink.RuntimeProps;
  adminSecClick?: Types.Devlink.RuntimeProps;
  adminSecSubMap?: Types.Devlink.Slot;
  adminExample?: Types.Visibility.VisibilityConditions;
  adminAvtrSrc?: Types.Asset.Image;
  adminAvtrAlt?: Types.Basic.AltText;
  adminTitleSrc?: React.ReactNode;
  adminSubtxtSrc?: React.ReactNode;
  adminClick?: Types.Devlink.RuntimeProps;
  mbrSecIcn?: React.ReactNode;
  mbrSecName?: React.ReactNode;
  mbrSecClick?: Types.Devlink.RuntimeProps;
  mbrSecSubMap?: Types.Devlink.Slot;
  mbrExample?: Types.Visibility.VisibilityConditions;
  mbrAvtrSrc?: Types.Asset.Image;
  mbrAvtrAlt?: Types.Basic.AltText;
  mbrTitleSrc?: React.ReactNode;
  mbrSubtxtSrc?: React.ReactNode;
  mbrClick?: Types.Devlink.RuntimeProps;
  mbrMoreClick?: Types.Devlink.RuntimeProps;
}): React.JSX.Element;
