import * as React from "react";
import * as Types from "./types";

declare function MMute(props: {
  as?: React.ElementType;
  mute?: Types.Visibility.VisibilityConditions;
  _15M?: Types.Visibility.VisibilityConditions;
  _15MOn?: Types.Visibility.VisibilityConditions;
  _1H?: Types.Visibility.VisibilityConditions;
  _1HOn?: Types.Visibility.VisibilityConditions;
  _3H?: Types.Visibility.VisibilityConditions;
  _3HOn?: Types.Visibility.VisibilityConditions;
  _8H?: Types.Visibility.VisibilityConditions;
  _8HOn?: Types.Visibility.VisibilityConditions;
  _24H?: Types.Visibility.VisibilityConditions;
  _24HOn?: Types.Visibility.VisibilityConditions;
  _2D?: Types.Visibility.VisibilityConditions;
  _2DOn?: Types.Visibility.VisibilityConditions;
  _1W?: Types.Visibility.VisibilityConditions;
  _1WOn?: Types.Visibility.VisibilityConditions;
  _2W?: Types.Visibility.VisibilityConditions;
  _2WOn?: Types.Visibility.VisibilityConditions;
  _1M?: Types.Visibility.VisibilityConditions;
  _1MOn?: Types.Visibility.VisibilityConditions;
  _3M?: Types.Visibility.VisibilityConditions;
  _3MOn?: Types.Visibility.VisibilityConditions;
  _6M?: Types.Visibility.VisibilityConditions;
  _6MOn?: Types.Visibility.VisibilityConditions;
  allOn?: Types.Visibility.VisibilityConditions;
  cancelClick?: Types.Devlink.RuntimeProps;
  _15MClick?: Types.Devlink.RuntimeProps;
  _1HClick?: Types.Devlink.RuntimeProps;
  _3HClick?: Types.Devlink.RuntimeProps;
  _8HClick?: Types.Devlink.RuntimeProps;
  _24HClick?: Types.Devlink.RuntimeProps;
  _2DClick?: Types.Devlink.RuntimeProps;
  _1WClick?: Types.Devlink.RuntimeProps;
  _2WClick?: Types.Devlink.RuntimeProps;
  _1MClick?: Types.Devlink.RuntimeProps;
  _3MClick?: Types.Devlink.RuntimeProps;
  _6MClick?: Types.Devlink.RuntimeProps;
  allClick?: Types.Devlink.RuntimeProps;
  doClick?: Types.Devlink.RuntimeProps;
}): React.JSX.Element;
