import * as React from "react";
import * as Types from "./types";

declare function MPostAdd(props: {
  as?: React.ElementType;
  postType?: React.ReactNode;
  cancelClick?: Types.Devlink.RuntimeProps;
  itmHead?: Types.Visibility.VisibilityConditions;
  itmImgSrc?: Types.Asset.Image;
  itmImgAlt?: Types.Basic.AltText;
  itmName?: React.ReactNode;
  upldUpldFldLblSrc?: React.ReactNode;
  upldUpldFileDzChange?: Types.Builtin.Text;
  upldUpldFileDzClick?: Types.Devlink.RuntimeProps;
  upldUpldBar?: Types.Visibility.VisibilityConditions;
  upldUpldBarFileMap?: Types.Devlink.Slot;
  upldExampleFileUpload?: Types.Visibility.VisibilityConditions;
  upldUpldBarFileImgSrc?: Types.Asset.Image;
  upldUpldBarFileImgAlt?: Types.Basic.AltText;
  upldUpldCapt?: Types.Visibility.VisibilityConditions;
  upldUpldBarFileTitleSrc?: React.ReactNode;
  upldUpldBarFileClick?: Types.Devlink.RuntimeProps;
  titleFldHelp?: Types.Visibility.VisibilityConditions;
  titleFldHelpL?: Types.Visibility.VisibilityConditions;
  titleFldHelpR?: Types.Visibility.VisibilityConditions;
  titleFldHelpLSrc?: React.ReactNode;
  titleFldHelpRSrc?: React.ReactNode;
  titleFldChange?: Types.Builtin.Text;
  titleFldClick?: Types.Devlink.RuntimeProps;
  bodyFldHelp?: Types.Visibility.VisibilityConditions;
  bodyFldHelpL?: Types.Visibility.VisibilityConditions;
  bodyFldHelpR?: Types.Visibility.VisibilityConditions;
  bodyFldHelpLSrc?: React.ReactNode;
  bodyFldHelpRSrc?: React.ReactNode;
  bodyFldChange?: Types.Builtin.Text;
  bodyFldClick?: Types.Devlink.RuntimeProps;
  upldFld?: Types.Visibility.VisibilityConditions;
  emojiBtn?: Types.Visibility.VisibilityConditions;
  emojiBtnIcnSrc?: React.ReactNode;
  emojiBtnClick?: Types.Devlink.RuntimeProps;
  doClick?: Types.Devlink.RuntimeProps;
  upldUpldFldHelp?: Types.Visibility.VisibilityConditions;
  upldUpldFldHelpL?: Types.Visibility.VisibilityConditions;
  upldUpldFldHelpR?: Types.Visibility.VisibilityConditions;
  upldUpldFldHelpLSrc?: React.ReactNode;
  upldUpldFldHelpRSrc?: React.ReactNode;
}): React.JSX.Element;
