import * as React from "react";
import * as Types from "./types";

declare function MSearch(props: {
  as?: React.ElementType;
  titleSrc?: React.ReactNode;
  cancelClick?: Types.Devlink.RuntimeProps;
  recent?: Types.Visibility.VisibilityConditions;
  recentNull?: Types.Visibility.VisibilityConditions;
  exampleRecentList?: Types.Visibility.VisibilityConditions;
  exampleHistory30?: Types.Visibility.VisibilityConditions;
  exampleHistoryold?: Types.Visibility.VisibilityConditions;
  recentMap?: Types.Devlink.Slot;
  result?: Types.Visibility.VisibilityConditions;
  resultNull?: Types.Visibility.VisibilityConditions;
  exampleResultList?: Types.Visibility.VisibilityConditions;
  resultMap?: Types.Devlink.Slot;
  history?: Types.Visibility.VisibilityConditions;
  clear30Click?: Types.Devlink.RuntimeProps;
  history30Map?: Types.Devlink.Slot;
  clearOldClick?: Types.Devlink.RuntimeProps;
  historyOldMap?: Types.Devlink.Slot;
  allClick?: Types.Devlink.RuntimeProps;
  allActive?: Types.Builtin.Text;
  listIcnSrc?: React.ReactNode;
  listActive?: Types.Builtin.Text;
  listClick?: Types.Devlink.RuntimeProps;
  peepIcnSrc?: React.ReactNode;
  peepActive?: Types.Builtin.Text;
  peepClick?: Types.Devlink.RuntimeProps;
  prodIcnSrc?: React.ReactNode;
  prodActive?: Types.Builtin.Text;
  prodClick?: Types.Devlink.RuntimeProps;
  placeIcnSrc?: React.ReactNode;
  placeActive?: Types.Builtin.Text;
  placeClick?: Types.Devlink.RuntimeProps;
  scanBtnClick?: Types.Devlink.RuntimeProps;
  searchPholdSrc?: Types.Builtin.Text;
  searchClick?: Types.Devlink.RuntimeProps;
  searchOnChange?: Types.Builtin.Text;
  searchClear?: Types.Visibility.VisibilityConditions;
  searchClearClick?: Types.Devlink.RuntimeProps;
  searchBtnClick?: Types.Devlink.RuntimeProps;
}): React.JSX.Element;
