import * as React from "react";
import * as Types from "./types";

declare function OlIconbarAction(props: {
  as?: React.ElementType;
  icnBar?: Types.Visibility.VisibilityConditions;
  l1Icn?: Types.Visibility.VisibilityConditions;
  r1Icn?: Types.Visibility.VisibilityConditions;
  l2Icn?: Types.Visibility.VisibilityConditions;
  r2Icn?: Types.Visibility.VisibilityConditions;
  l3Icn?: Types.Visibility.VisibilityConditions;
  r3Icn?: Types.Visibility.VisibilityConditions;
  l1IcnL1Src?: React.ReactNode;
  r1IcnR1Src?: React.ReactNode;
  r1IcnR1Clr?: Types.Builtin.Text;
  r1IcnR1Link?: Types.Basic.Link;
  r1IcnR1Click?: Types.Devlink.RuntimeProps;
  l2IcnL2Src?: React.ReactNode;
  l2IcnL2Clr?: Types.Builtin.Text;
  l2IcnL2Link?: Types.Basic.Link;
  l2IcnL2Click?: Types.Devlink.RuntimeProps;
  r2IcnR2Src?: React.ReactNode;
  r2IcnR2Clr?: Types.Builtin.Text;
  r2IcnR2Link?: Types.Basic.Link;
  r2IcnR2Click?: Types.Devlink.RuntimeProps;
  l3IcnL3Src?: React.ReactNode;
  l3IcnL3Clr?: Types.Builtin.Text;
  l3IcnL3Link?: Types.Basic.Link;
  l3IcnL3Click?: Types.Devlink.RuntimeProps;
  r3IcnR3Src?: React.ReactNode;
  r3IcnR3Clr?: Types.Builtin.Text;
  r3IcnR3Link?: Types.Basic.Link;
  r3IcnR3Click?: Types.Devlink.RuntimeProps;
  l1IcnL1Clr?: Types.Builtin.Text;
  l1IcnL1Link?: Types.Basic.Link;
  l1IcnL1Click?: Types.Devlink.RuntimeProps;
  l1IcnL1DrpShdw?: Types.Builtin.Text;
  l2IcnL2DrpShdw?: Types.Builtin.Text;
  l3IcnL3DrpShdw?: Types.Builtin.Text;
  r3IcnR3DrpShdw?: Types.Builtin.Text;
  r2IcnR2DrpShdw?: Types.Builtin.Text;
  r1IcnR1DrpShdw?: Types.Builtin.Text;
}): React.JSX.Element;
