import * as React from "react";
import * as Types from "./types";

declare function P1Grid(props: {
  as?: React.ElementType;
  slotId?: Types.Basic.IdTextInput;
  p1Grid?: Types.Visibility.VisibilityConditions;
  p1Map?: Types.Devlink.Slot;
  p1Example?: Types.Visibility.VisibilityConditions;
  p1Group?: Types.Visibility.VisibilityConditions;
  p1Peep?: Types.Visibility.VisibilityConditions;
  p1GroupImgSrc?: Types.Asset.Image;
  p1PeepAvtrSrc?: Types.Asset.Image;
  p1PeepAvtrBdgClr?: Types.Builtin.Text;
  p1GroupImgAlt?: Types.Basic.AltText;
  p1ProfName?: React.ReactNode;
  p1ProfClick?: Types.Devlink.RuntimeProps;
  p1ChatBtnClick?: Types.Devlink.RuntimeProps;
  p1MoreBtnClick?: Types.Devlink.RuntimeProps;
  p1ListQty?: React.ReactNode;
  p1LsAdpt1IcnSrc?: React.ReactNode;
  p1LsAdpt1BgClr?: Types.Builtin.Text;
  p1LsAdpt2BgClr?: Types.Builtin.Text;
  p1LsAdpt2CnSrc?: React.ReactNode;
  p1LsAdpt3BgClr?: Types.Builtin.Text;
  p1LsAdpt3IcnSrc?: React.ReactNode;
  p1ListClick?: Types.Devlink.RuntimeProps;
  p1PeepQty?: React.ReactNode;
  p1PeepAvtr1Src?: Types.Asset.Image;
  p1PeepAvtr2Src?: Types.Asset.Image;
  p1PeepAvtr3Src?: Types.Asset.Image;
  p1PeepClick?: Types.Devlink.RuntimeProps;
  p1CalQty?: React.ReactNode;
  p1CalAdpt1IcnSrc?: React.ReactNode;
  p1CalAdpt1BgClr?: Types.Builtin.Text;
  p1CalAdpt2BgClr?: Types.Builtin.Text;
  p1CalAdpt2CnSrc?: React.ReactNode;
  p1CalAdpt3BgClr?: Types.Builtin.Text;
  p1CalAdpt3IcnSrc?: React.ReactNode;
  p1CalClick?: Types.Devlink.RuntimeProps;
  exampleCell?: Types.Visibility.VisibilityConditions;
}): React.JSX.Element;
