import * as React from "react";
import * as Types from "./types";

declare function PAccSettings(props: {
  as?: React.ElementType;
  themeSelectDrpHide?: Types.Visibility.VisibilityConditions;
  themePHoldSrc?: React.ReactNode;
  themePHoldClr?: Types.Builtin.Text;
  themeMap?: Types.Devlink.Slot;
  modeClick?: Types.Devlink.RuntimeProps;
  languageSelectDrpHide?: Types.Visibility.VisibilityConditions;
  languagePHoldSrc?: React.ReactNode;
  languagePHoldClr?: Types.Builtin.Text;
  languageMap?: Types.Devlink.Slot;
  countrySelectDrpHide?: Types.Visibility.VisibilityConditions;
  countryPHoldSrc?: React.ReactNode;
  countryPHoldClr?: Types.Builtin.Text;
  countryMap?: Types.Devlink.Slot;
  currencySelectDrpHide?: Types.Visibility.VisibilityConditions;
  currencyPHoldSrc?: React.ReactNode;
  currencyPHoldClr?: Types.Builtin.Text;
  currencyMap?: Types.Devlink.Slot;
  measureSelectDrpHide?: Types.Visibility.VisibilityConditions;
  measurePHoldSrc?: React.ReactNode;
  measurePHoldClr?: Types.Builtin.Text;
  measureMap?: Types.Devlink.Slot;
  zoneSelectDrpHide?: Types.Visibility.VisibilityConditions;
  zonePHoldSrc?: React.ReactNode;
  zonePHoldClr?: Types.Builtin.Text;
  zoneMap?: Types.Devlink.Slot;
  permAllClick?: Types.Devlink.RuntimeProps;
  permLocClick?: Types.Devlink.RuntimeProps;
  permCamClick?: Types.Devlink.RuntimeProps;
  permContClick?: Types.Devlink.RuntimeProps;
  permCalClick?: Types.Devlink.RuntimeProps;
  permLibClick?: Types.Devlink.RuntimeProps;
  permMicClick?: Types.Devlink.RuntimeProps;
  doClick?: Types.Devlink.RuntimeProps;
}): React.JSX.Element;
