import * as React from "react";
import * as Types from "./types";

declare function PBrand(props: {
  as?: React.ElementType;
  heroImgSrc?: Types.Asset.Image;
  heroAvtrSrc?: Types.Asset.Image;
  heroName?: React.ReactNode;
  heroSubtxtSrc?: React.ReactNode;
  heroQrClick?: Types.Devlink.RuntimeProps;
  heroMoreClick?: Types.Devlink.RuntimeProps;
  heroBtn?: Types.Visibility.VisibilityConditions;
  heroBtnClick?: Types.Devlink.RuntimeProps;
  scanQrBtnClick?: Types.Devlink.RuntimeProps;
  searchFldClick?: Types.Devlink.RuntimeProps;
  favClick?: Types.Devlink.RuntimeProps;
  chatClick?: Types.Devlink.RuntimeProps;
  honorClick?: Types.Devlink.RuntimeProps;
  alertClick?: Types.Devlink.RuntimeProps;
  popMap?: Types.Devlink.Slot;
  examplePopProduct?: Types.Visibility.VisibilityConditions;
  examplePopVizSrc?: Types.Asset.Image;
  examplePopVizAlt?: Types.Basic.AltText;
  examplePopActClick?: Types.Devlink.RuntimeProps;
  rank?: Types.Visibility.VisibilityConditions;
  peep?: Types.Visibility.VisibilityConditions;
  examplePopCellClick?: Types.Devlink.RuntimeProps;
  list?: Types.Visibility.VisibilityConditions;
  offer?: Types.Visibility.VisibilityConditions;
  brand?: Types.Visibility.VisibilityConditions;
  places?: Types.Visibility.VisibilityConditions;
  activity?: Types.Visibility.VisibilityConditions;
  body1Map?: Types.Devlink.Slot;
  body2Map?: Types.Devlink.Slot;
  body3Map?: Types.Devlink.Slot;
  body4Map?: Types.Devlink.Slot;
  body5Map?: Types.Devlink.Slot;
  body6Map?: Types.Devlink.Slot;
  body7Map?: Types.Devlink.Slot;
}): React.JSX.Element;
