import * as React from "react";
import * as Types from "./types";

declare function PFileAdd(props: {
  as?: React.ElementType;
  titleSrc?: React.ReactNode;
  cancelClick?: Types.Devlink.RuntimeProps;
  itmHead?: Types.Visibility.VisibilityConditions;
  itmImgSrc?: Types.Asset.Image;
  itmImgAlt?: Types.Basic.AltText;
  itmName?: React.ReactNode;
  typeFld?: Types.Visibility.VisibilityConditions;
  typePHoldSrc?: React.ReactNode;
  typePHoldClr?: Types.Builtin.Text;
  typeSelectDrpHide?: Types.Visibility.VisibilityConditions;
  typeFldMap?: Types.Devlink.Slot;
  titleFld?: Types.Visibility.VisibilityConditions;
  titleFldChars?: React.ReactNode;
  titleFldChange?: Types.Builtin.Text;
  titleFldClick?: Types.Devlink.RuntimeProps;
  upldUpldFld?: Types.Visibility.VisibilityConditions;
  upldUpldFldLblSrc?: React.ReactNode;
  upldUpldFldOptSrc?: React.ReactNode;
  upldUpldFileDzChange?: Types.Builtin.Text;
  upldUpldFileDzClick?: Types.Devlink.RuntimeProps;
  upldUpldBar?: Types.Visibility.VisibilityConditions;
  upldUpldBarFileMap?: Types.Devlink.Slot;
  upldExampleFileUpload?: Types.Visibility.VisibilityConditions;
  upldUpldBarFileImgSrc?: Types.Asset.Image;
  upldUpldBarFileImgAlt?: Types.Basic.AltText;
  upldUpldBarFileTitleSrc?: React.ReactNode;
  upldUpldBarFileClick?: Types.Devlink.RuntimeProps;
  doClick?: Types.Devlink.RuntimeProps;
  upldUpldOpt?: Types.Visibility.VisibilityConditions;
  upldUpldOptCamera?: Types.Visibility.VisibilityConditions;
  upldUpldOptLib?: Types.Visibility.VisibilityConditions;
  upldUpldOptUnsplash?: Types.Visibility.VisibilityConditions;
  upldUpldOptUrl?: Types.Visibility.VisibilityConditions;
  upldUpldOptCameraClick?: Types.Devlink.RuntimeProps;
  upldUpldOptLibClick?: Types.Devlink.RuntimeProps;
  upldUpldOptUnsplashClick?: Types.Devlink.RuntimeProps;
  upldUpldOptUrlClick?: Types.Devlink.RuntimeProps;
  upldUpldUrl?: Types.Visibility.VisibilityConditions;
  upldUpldUrlFldChange?: Types.Builtin.Text;
  upldUpldUrlFldClick?: Types.Devlink.RuntimeProps;
  upldUpldUrlBtnGetClick?: Types.Devlink.RuntimeProps;
}): React.JSX.Element;
