import * as React from "react";
import * as Types from "./types";

declare function PGroupDetail(props: {
  as?: React.ElementType;
  heroImgSrc?: Types.Asset.Image;
  heroTitle?: React.ReactNode;
  heroSubtxt?: React.ReactNode;
  heroQrClick?: Types.Devlink.RuntimeProps;
  heroMoreClick?: Types.Devlink.RuntimeProps;
  heroBtn?: Types.Visibility.VisibilityConditions;
  heroBtnTxtSrc?: React.ReactNode;
  heroBtnIcnSrc?: React.ReactNode;
  heroBtnClick?: Types.Devlink.RuntimeProps;
  scanQrBtnClick?: Types.Devlink.RuntimeProps;
  inviteClick?: Types.Devlink.RuntimeProps;
  roomAdd?: Types.Visibility.VisibilityConditions;
  roomAddClick?: Types.Devlink.RuntimeProps;
  roomMap?: Types.Devlink.Slot;
  roomMsgQty?: React.ReactNode;
  roomLikeQty?: React.ReactNode;
  roomPeepQty?: React.ReactNode;
  galAdd?: Types.Visibility.VisibilityConditions;
  galAddClick?: Types.Devlink.RuntimeProps;
  galMap?: Types.Devlink.Slot;
  galPhotoQty?: React.ReactNode;
  galVidQty?: React.ReactNode;
  galPeepQty?: React.ReactNode;
  attAdd?: Types.Visibility.VisibilityConditions;
  attAddClick?: Types.Devlink.RuntimeProps;
  attListMap?: Types.Devlink.Slot;
  attPlaceMap?: Types.Devlink.Slot;
  mbrAdd?: Types.Visibility.VisibilityConditions;
  mbrAddClick?: Types.Devlink.RuntimeProps;
  mbrAdminMap?: Types.Devlink.Slot;
  mbrAvtrMap?: Types.Devlink.Slot;
  mbrFamQty?: React.ReactNode;
  mbrFriQty?: React.ReactNode;
  mbrAllQty?: React.ReactNode;
  exampleList?: Types.Visibility.VisibilityConditions;
  examplePlaces?: Types.Visibility.VisibilityConditions;
  exampleGallery?: Types.Visibility.VisibilityConditions;
  exampleMbrs?: Types.Visibility.VisibilityConditions;
}): React.JSX.Element;
