import * as React from "react";
import * as Types from "./types";

declare function PItemRev(props: {
  as?: React.ElementType;
  itmImgSrc?: Types.Asset.Image;
  itmImgAlt?: Types.Basic.AltText;
  itmName?: React.ReactNode;
  rateAvgValue?: React.ReactNode;
  rateQty?: React.ReactNode;
  rateBar1Qty?: Types.Devlink.RuntimeProps;
  rateBar2Qty?: Types.Devlink.RuntimeProps;
  rateBar3Qty?: Types.Devlink.RuntimeProps;
  rateBar4Qty?: Types.Devlink.RuntimeProps;
  rateBar5Qty?: Types.Devlink.RuntimeProps;
  rateBar1Click?: Types.Devlink.RuntimeProps;
  rateBar2Click?: Types.Devlink.RuntimeProps;
  rateBar3Click?: Types.Devlink.RuntimeProps;
  rateBar4Click?: Types.Devlink.RuntimeProps;
  rateBar5Click?: Types.Devlink.RuntimeProps;
  giveClick?: Types.Devlink.RuntimeProps;
  scanBtn?: Types.Visibility.VisibilityConditions;
  scanBtnClick?: Types.Devlink.RuntimeProps;
  searchClick?: Types.Devlink.RuntimeProps;
  searchChange?: Types.Builtin.Text;
  fltrBtn?: Types.Visibility.VisibilityConditions;
  fltrClick?: Types.Devlink.RuntimeProps;
  postMap?: Types.Devlink.Slot;
  postExample?: Types.Visibility.VisibilityConditions;
  mediaAllClick?: Types.Devlink.RuntimeProps;
  mediaMap?: Types.Devlink.Slot;
  mediaExample?: Types.Visibility.VisibilityConditions;
  peep?: Types.Visibility.VisibilityConditions;
  peepMap?: Types.Devlink.Slot;
  peepExample?: Types.Visibility.VisibilityConditions;
  peepStat1Src?: React.ReactNode;
  peepStat2Src?: React.ReactNode;
  slotId?: Types.Basic.IdTextInput;
}): React.JSX.Element;
