import * as React from "react";
import * as Types from "./types";

declare function PItemGroup(props: {
  as?: React.ElementType;
  heroGttrPin?: Types.Visibility.VisibilityConditions;
  heroGttrBkmrk?: Types.Visibility.VisibilityConditions;
  heroImgSrc?: Types.Asset.Image;
  heroImgAlt?: Types.Basic.AltText;
  heroTitle?: React.ReactNode;
  heroAvtr?: Types.Asset.Image;
  heroAvtrAlt?: Types.Basic.AltText;
  heroAvtr2?: Types.Visibility.VisibilityConditions;
  heroAvtr3?: Types.Visibility.VisibilityConditions;
  heroAvtr4?: Types.Visibility.VisibilityConditions;
  heroAvtr5?: Types.Visibility.VisibilityConditions;
  heroAvtr2Src?: Types.Asset.Image;
  heroAvtr2Alt?: Types.Basic.AltText;
  heroAvtr3Src?: Types.Asset.Image;
  heroAvtr3Alt?: Types.Basic.AltText;
  heroAvtr4Src?: Types.Asset.Image;
  heroAvtr4Alt?: Types.Basic.AltText;
  heroAvtr5Src?: Types.Asset.Image;
  heroAvtr5Alt?: Types.Basic.AltText;
  heroMbr?: React.ReactNode;
  heroTime?: React.ReactNode;
  heroClick?: Types.Devlink.RuntimeProps;
  heroMoreClick?: Types.Devlink.RuntimeProps;
  groupAddClick?: Types.Devlink.RuntimeProps;
  scanBtn?: Types.Visibility.VisibilityConditions;
  scanBtnClick?: Types.Devlink.RuntimeProps;
  searchClick?: Types.Devlink.RuntimeProps;
  searchChange?: Types.Builtin.Text;
  fltrBtn?: Types.Visibility.VisibilityConditions;
  fltrClick?: Types.Devlink.RuntimeProps;
  postMap?: Types.Devlink.Slot;
  postExample?: Types.Visibility.VisibilityConditions;
  pop?: Types.Visibility.VisibilityConditions;
  popMap?: Types.Devlink.Slot;
  popExample?: Types.Visibility.VisibilityConditions;
  peep?: Types.Visibility.VisibilityConditions;
  peepMap?: Types.Devlink.Slot;
  peepExample?: Types.Visibility.VisibilityConditions;
  peepStat1Src?: React.ReactNode;
  peepStat2Src?: React.ReactNode;
  slotIdGrid?: Types.Basic.IdTextInput;
  slotIdPop?: Types.Basic.IdTextInput;
}): React.JSX.Element;
