import * as React from "react";
import * as Types from "./types";

declare function PItemMarket(props: {
  as?: React.ElementType;
  heroImgSrc?: Types.Asset.Image;
  heroImgAlt?: Types.Basic.AltText;
  heroImgClick?: Types.Devlink.RuntimeProps;
  heroPrimeClick?: Types.Devlink.RuntimeProps;
  heroAvtrSrc?: Types.Asset.Image;
  heroAvtrAlt?: Types.Basic.AltText;
  heroTitleSrc?: React.ReactNode;
  heroSubtxt1Src?: React.ReactNode;
  heroSuprActClick?: Types.Devlink.RuntimeProps;
  askClick?: Types.Devlink.RuntimeProps;
  searchChange?: Types.Builtin.Text;
  searchClick?: Types.Devlink.RuntimeProps;
  fltrAllClick?: Types.Devlink.RuntimeProps;
  fltrAllActive?: Types.Builtin.Text;
  fltrRetailClick?: Types.Devlink.RuntimeProps;
  fltrRetailActive?: Types.Builtin.Text;
  fltrBrand?: Types.Visibility.VisibilityConditions;
  fltrBrandClick?: Types.Devlink.RuntimeProps;
  fltrBrandActive?: Types.Builtin.Text;
  fltrAuc?: Types.Visibility.VisibilityConditions;
  fltrAucClick?: Types.Devlink.RuntimeProps;
  fltrAucActive?: Types.Builtin.Text;
  fltrClass?: Types.Visibility.VisibilityConditions;
  fltrClassClick?: Types.Devlink.RuntimeProps;
  fltrClassActive?: Types.Builtin.Text;
  offerMap?: Types.Devlink.Slot;
  appliedMap?: Types.Devlink.Slot;
  appliedExample?: Types.Visibility.VisibilityConditions;
  appliedItmClick?: Types.Devlink.RuntimeProps;
  placeHeadAct1Click?: Types.Devlink.RuntimeProps;
  placeCellMap?: Types.Devlink.Slot;
  exampleCellPlace?: Types.Visibility.VisibilityConditions;
  placeCellActv?: Types.Visibility.VisibilityConditions;
}): React.JSX.Element;
