import * as React from "react";
import * as Types from "./types";

declare function POffer1(props: {
  as?: React.ElementType;
  heroImgSrc?: Types.Asset.Image;
  heroImgAlt?: Types.Basic.AltText;
  heroHlineSrc?: React.ReactNode;
  heroSubtxt?: Types.Visibility.VisibilityConditions;
  heroSubtxtSrc?: React.ReactNode;
  heroQrClick?: Types.Devlink.RuntimeProps;
  heroMoreClick?: Types.Devlink.RuntimeProps;
  scanQrBtnClick?: Types.Devlink.RuntimeProps;
  searchClick?: Types.Devlink.RuntimeProps;
  favClick?: Types.Devlink.RuntimeProps;
  addClick?: Types.Devlink.RuntimeProps;
  highRate?: Types.Visibility.VisibilityConditions;
  hrMap?: Types.Devlink.Slot;
  exampleHighRateCell?: Types.Visibility.VisibilityConditions;
  bodySecMap?: Types.Devlink.Slot;
  categories?: Types.Visibility.VisibilityConditions;
  featured?: Types.Visibility.VisibilityConditions;
  prodOff?: Types.Visibility.VisibilityConditions;
  brands?: Types.Visibility.VisibilityConditions;
  hrCellHeadTitleIcn?: Types.Visibility.VisibilityConditions;
  hrCellHeadAct1?: Types.Visibility.VisibilityConditions;
  hrCellHeadTitleIcnSrc?: React.ReactNode;
  hrCellHeadTitleSrc?: React.ReactNode;
  hrCellHeadAct1TxtSrc?: React.ReactNode;
  hrCellHeadAct1Click?: Types.Devlink.RuntimeProps;
  hrCellVizSrc?: Types.Asset.Image;
  hrCellVizAlt?: Types.Basic.AltText;
  hrCellNameSrc?: React.ReactNode;
  hrCellHookSrc?: React.ReactNode;
  hrCellByVizSrc?: Types.Asset.Image;
  hrCellTypeSrc?: React.ReactNode;
  hrCellLimitSrc?: React.ReactNode;
  hrCellActClick?: Types.Devlink.RuntimeProps;
  hrCellCellClick?: Types.Devlink.RuntimeProps;
}): React.JSX.Element;
