import * as React from "react";
import * as Types from "./types";

declare function SecClip(props: {
  as?: React.ElementType;
  sec?: Types.Visibility.VisibilityConditions;
  secHead?: Types.Visibility.VisibilityConditions;
  stats?: Types.Visibility.VisibilityConditions;
  secHeadTitleIcn?: Types.Visibility.VisibilityConditions;
  secHeadAct1?: Types.Visibility.VisibilityConditions;
  secHeadTitleIcnSrc?: React.ReactNode;
  secHeadTitleSrc?: React.ReactNode;
  secHeadAct1TxtSrc?: React.ReactNode;
  secHeadAct1Click?: Types.Devlink.RuntimeProps;
  conSideFade?: Types.Visibility.VisibilityConditions;
  conCellMap?: Types.Devlink.Slot;
  conSlotId?: Types.Basic.IdTextInput;
  conCellExample?: Types.Visibility.VisibilityConditions;
  exampleVizSrc?: Types.Asset.Image;
  exampleVizAlt?: Types.Basic.AltText;
  exampleVizSz?: Types.Builtin.Text;
  exampleVizAsp?: Types.Builtin.Text;
  exampleCapt?: Types.Visibility.VisibilityConditions;
  exampleCaptTitleSrc?: React.ReactNode;
  exampleTypeSrc?: React.ReactNode;
  exampleLimitSrc?: React.ReactNode;
  exampleExpSrc?: React.ReactNode;
  exampleCellSz?: Types.Builtin.Text;
  exampleCellCard?: Types.Builtin.Text;
  exampleCellClick?: Types.Devlink.RuntimeProps;
  exampleEmpty?: Types.Visibility.VisibilityConditions;
  exampleEmptyIcnSrc?: React.ReactNode;
  exampleEmptyHlineSrc?: React.ReactNode;
  exampleEmptySubTxtSrc?: React.ReactNode;
  exampleEmptyCtaTxtSrc?: React.ReactNode;
  exampleEmptyClick?: Types.Devlink.RuntimeProps;
  stat1Src?: React.ReactNode;
  stat2Src?: React.ReactNode;
  stat3Src?: React.ReactNode;
  stat4Src?: React.ReactNode;
  stat2?: Types.Visibility.VisibilityConditions;
  stat3?: Types.Visibility.VisibilityConditions;
  stat4?: Types.Visibility.VisibilityConditions;
}): React.JSX.Element;
