import * as React from "react";
import * as Types from "./types";

declare function SecList(props: {
  as?: React.ElementType;
  sec?: Types.Visibility.VisibilityConditions;
  secHead?: Types.Visibility.VisibilityConditions;
  secHeadTitleIcn?: Types.Visibility.VisibilityConditions;
  secHeadAct1?: Types.Visibility.VisibilityConditions;
  secHeadAct1Icn?: Types.Visibility.VisibilityConditions;
  secHeadAct1Txt?: Types.Visibility.VisibilityConditions;
  secHeadTitleIcnSrc?: React.ReactNode;
  secHeadTitleSrc?: React.ReactNode;
  secHeadAct1IcnSrc?: React.ReactNode;
  secHeadAct1TxtSrc?: React.ReactNode;
  secHeadAct1Click?: Types.Devlink.RuntimeProps;
  conSideFade?: Types.Visibility.VisibilityConditions;
  conCellMap?: Types.Devlink.Slot;
  conSlotId?: Types.Basic.IdTextInput;
  conCellExample?: Types.Visibility.VisibilityConditions;
  exampleVizSrc?: Types.Asset.Image;
  exampleVizAlt?: Types.Basic.AltText;
  exampleVizAsp?: Types.Builtin.Text;
  exampleVizSz?: Types.Builtin.Text;
  exampleBnr?: Types.Visibility.VisibilityConditions;
  exampleBnrIcnSrc?: React.ReactNode;
  exampleBnrTxtSrc?: React.ReactNode;
  exampleCapt?: Types.Visibility.VisibilityConditions;
  exampleTitleSrc?: React.ReactNode;
  exampleCellSz?: Types.Builtin.Text;
  exampleCellCard?: Types.Builtin.Text;
  exampleCellClick?: Types.Devlink.RuntimeProps;
  stats?: Types.Visibility.VisibilityConditions;
  stat1Src?: React.ReactNode;
  stat2Src?: React.ReactNode;
  stat3Src?: React.ReactNode;
  stat4Src?: React.ReactNode;
  stat2?: Types.Visibility.VisibilityConditions;
  stat3?: Types.Visibility.VisibilityConditions;
  stat4?: Types.Visibility.VisibilityConditions;
  emptyEmpty?: Types.Visibility.VisibilityConditions;
  emptyEmptyIcnSrc?: React.ReactNode;
  emptyEmptyHlineSrc?: React.ReactNode;
  emptyEmptySubTxtSrc?: React.ReactNode;
  emptyEmptyCtaTxtSrc?: React.ReactNode;
  emptyEmptyClick?: Types.Devlink.RuntimeProps;
}): React.JSX.Element;
