import * as React from "react";
import * as Types from "./types";

declare function SecOffer(props: {
  as?: React.ElementType;
  sec?: Types.Visibility.VisibilityConditions;
  secHead?: Types.Visibility.VisibilityConditions;
  secHeadTitleIcn?: Types.Visibility.VisibilityConditions;
  conSideFade?: Types.Visibility.VisibilityConditions;
  conCellMap?: Types.Devlink.Slot;
  conSlotId?: Types.Basic.IdTextInput;
  conExampleCell?: Types.Visibility.VisibilityConditions;
  exampleVizSrc?: Types.Asset.Image;
  exampleVizAlt?: Types.Basic.AltText;
  exampleVizSz?: Types.Builtin.Text;
  exampleCapt?: Types.Visibility.VisibilityConditions;
  exampleNameSrc?: React.ReactNode;
  exampleHookSrc?: React.ReactNode;
  exampleByVizSrc?: Types.Asset.Image;
  exampleTypeSrc?: React.ReactNode;
  exampleLimitSrc?: React.ReactNode;
  exampleCellSz?: Types.Builtin.Text;
  exampleCellCard?: Types.Builtin.Text;
  exampleActClick?: Types.Devlink.RuntimeProps;
  exampleCellClick?: Types.Devlink.RuntimeProps;
  secHeadAct1?: Types.Visibility.VisibilityConditions;
  secHeadTitleIcnSrc?: React.ReactNode;
  secHeadTitleSrc?: React.ReactNode;
  secHeadTitleSz?: Types.Builtin.Text;
  secHeadTitleClr?: Types.Builtin.Text;
  secHeadAct1TxtSrc?: React.ReactNode;
  secHeadAct1Click?: Types.Devlink.RuntimeProps;
  stats?: Types.Visibility.VisibilityConditions;
  stat1Src?: React.ReactNode;
  stat2Src?: React.ReactNode;
  stat3Src?: React.ReactNode;
  stat4Src?: React.ReactNode;
  stat2?: Types.Visibility.VisibilityConditions;
  stat3?: Types.Visibility.VisibilityConditions;
  stat4?: Types.Visibility.VisibilityConditions;
  emptyEmpty?: Types.Visibility.VisibilityConditions;
  emptyEmptyIcnSrc?: React.ReactNode;
  emptyEmptyHlineSrc?: React.ReactNode;
  emptyEmptySubTxtSrc?: React.ReactNode;
  emptyEmptyCtaTxtSrc?: React.ReactNode;
  emptyEmptyClick?: Types.Devlink.RuntimeProps;
  conBarPad?: Types.Builtin.Text;
}): React.JSX.Element;
