import * as React from "react";
import * as Types from "./types";

declare function SecPlaceChoice(props: {
  as?: React.ElementType;
  sec?: Types.Visibility.VisibilityConditions;
  secHead?: Types.Visibility.VisibilityConditions;
  secHeadTitleIcn?: Types.Visibility.VisibilityConditions;
  secHeadAct1?: Types.Visibility.VisibilityConditions;
  secHeadTitleIcnSrc?: React.ReactNode;
  secHeadTitleSrc?: React.ReactNode;
  secHeadAct1TxtSrc?: React.ReactNode;
  secHeadAct1Click?: Types.Devlink.RuntimeProps;
  conSideFade?: Types.Visibility.VisibilityConditions;
  conCellMap?: Types.Devlink.Slot;
  conExampleCell?: Types.Visibility.VisibilityConditions;
  exampleCellActv?: Types.Visibility.VisibilityConditions;
  exampleVizSrc?: React.ReactNode;
  exampleVizSz?: Types.Builtin.Text;
  exampleVizClr?: Types.Builtin.Text;
  exampleCapt?: Types.Visibility.VisibilityConditions;
  exampleCaptTitleSrc?: React.ReactNode;
  exampleCaptSubtxtSrc?: React.ReactNode;
  exampleCaptSub2Src?: React.ReactNode;
  exampleCellSz?: Types.Builtin.Text;
  exampleCellCard?: Types.Builtin.Text;
  exampleCellClick?: Types.Devlink.RuntimeProps;
  stats?: Types.Visibility.VisibilityConditions;
  stat1Src?: React.ReactNode;
  stat2Src?: React.ReactNode;
  stat3Src?: React.ReactNode;
  stat4Src?: React.ReactNode;
  stat2?: Types.Visibility.VisibilityConditions;
  stat3?: Types.Visibility.VisibilityConditions;
  stat4?: Types.Visibility.VisibilityConditions;
  emptyEmpty?: Types.Visibility.VisibilityConditions;
  emptyEmptyIcnSrc?: React.ReactNode;
  emptyEmptyHlineSrc?: React.ReactNode;
  emptyEmptySubTxtSrc?: React.ReactNode;
  emptyEmptyCtaTxtSrc?: React.ReactNode;
  emptyEmptyClick?: Types.Devlink.RuntimeProps;
}): React.JSX.Element;
