import * as React from "react";
import * as Types from "./types";

declare function SegBtnCtrl(props: {
  as?: React.ElementType;
  segBtn?: Types.Visibility.VisibilityConditions;
  btn1?: Types.Visibility.VisibilityConditions;
  btn2?: Types.Visibility.VisibilityConditions;
  btn3?: Types.Visibility.VisibilityConditions;
  btn4?: Types.Visibility.VisibilityConditions;
  btn5?: Types.Visibility.VisibilityConditions;
  segBtnClr?: Types.Builtin.Text;
  btn1Btn1Txt?: Types.Visibility.VisibilityConditions;
  btn1Btn1Icn?: Types.Visibility.VisibilityConditions;
  btn1Btn1TxtSrc?: React.ReactNode;
  btn1Btn1IcnSrc?: React.ReactNode;
  btn1Btn1Actv?: Types.Builtin.Text;
  btn1Btn1Click?: Types.Devlink.RuntimeProps;
  btn2Btn2Txt?: Types.Visibility.VisibilityConditions;
  btn2Btn2Icn?: Types.Visibility.VisibilityConditions;
  btn2Btn2TxtSrc?: React.ReactNode;
  btn2Btn2IcnSrc?: React.ReactNode;
  btn2Btn2Actv?: Types.Builtin.Text;
  btn2Btn2Click?: Types.Devlink.RuntimeProps;
  btn3Btn3Txt?: Types.Visibility.VisibilityConditions;
  btn3Btn3Icn?: Types.Visibility.VisibilityConditions;
  btn3Btn3TxtSrc?: React.ReactNode;
  btn3Btn3IcnSrc?: React.ReactNode;
  btn3Btn3Actv?: Types.Builtin.Text;
  btn3Btn3Click?: Types.Devlink.RuntimeProps;
  btn4Btn4Txt?: Types.Visibility.VisibilityConditions;
  btn4Btn4Icn?: Types.Visibility.VisibilityConditions;
  btn4Btn4TxtSrc?: React.ReactNode;
  btn4Btn4IcnSrc?: React.ReactNode;
  btn4Btn4Actv?: Types.Builtin.Text;
  btn4Btn4Click?: Types.Devlink.RuntimeProps;
  btn5Btn5Txt?: Types.Visibility.VisibilityConditions;
  btn5Btn5Icn?: Types.Visibility.VisibilityConditions;
  btn5Btn5TxtSrc?: React.ReactNode;
  btn5Btn5IcnSrc?: React.ReactNode;
  btn5Btn5Actv?: Types.Builtin.Text;
  btn5Btn5Click?: Types.Devlink.RuntimeProps;
}): React.JSX.Element;
