import * as React from "react";
import * as Types from "./types";

declare function SelectlistForm(props: {
  as?: React.ElementType;
  fld?: Types.Visibility.VisibilityConditions;
  lblTop?: Types.Visibility.VisibilityConditions;
  fldHelp?: Types.Visibility.VisibilityConditions;
  fbk?: Types.Visibility.VisibilityConditions;
  lblTopLblSrc?: React.ReactNode;
  lblTopLblFor?: Types.Builtin.Text;
  lblTopLblSz?: Types.Builtin.Text;
  lblTopLblClr?: Types.Builtin.Text;
  lblTopLblShdw?: Types.Builtin.Text;
  lblTopOpt?: Types.Visibility.VisibilityConditions;
  lblTopOptSrc?: React.ReactNode;
  lblTopOptSz?: Types.Builtin.Text;
  lblTopOptClr?: Types.Builtin.Text;
  fieldFldId?: Types.Basic.IdTextInput;
  fieldFldValue?: Types.Builtin.Text;
  fieldPHoldSrc?: React.ReactNode;
  fieldPHoldClr?: Types.Builtin.Text;
  fieldFldBrdClr?: Types.Builtin.Text;
  fieldSelectDrpHide?: Types.Visibility.VisibilityConditions;
  fieldSelectMap?: Types.Devlink.Slot;
  fldHelpHelpL?: Types.Visibility.VisibilityConditions;
  fldHelpHelpR?: Types.Visibility.VisibilityConditions;
  fldHelpHelpLSrc?: React.ReactNode;
  fldHelpHelpRSrc?: React.ReactNode;
  fbkFbkTxt?: Types.Visibility.VisibilityConditions;
  fbkFbkIcn?: Types.Visibility.VisibilityConditions;
  fbkFbkTxtSrc?: React.ReactNode;
  fbkFbkIcnSrc?: React.ReactNode;
  fbkFbkClr?: Types.Builtin.Text;
  fldHelpHelpShdw?: Types.Builtin.Text;
  fieldOnChange?: Types.Builtin.Text;
}): React.JSX.Element;
