import * as React from "react";
import * as Types from "./types";

declare function SnipSecMedia(props: {
  as?: React.ElementType;
  sec?: Types.Visibility.VisibilityConditions;
  secHead?: Types.Visibility.VisibilityConditions;
  stats?: Types.Visibility.VisibilityConditions;
  secHeadTitleIcn?: Types.Visibility.VisibilityConditions;
  secHeadAct1?: Types.Visibility.VisibilityConditions;
  secHeadAct1Icn?: Types.Visibility.VisibilityConditions;
  secHeadAct1Txt?: Types.Visibility.VisibilityConditions;
  secHeadTitleIcnSrc?: React.ReactNode;
  secHeadTitleSrc?: React.ReactNode;
  secHeadAct1IcnSrc?: React.ReactNode;
  secHeadAct1TxtSrc?: React.ReactNode;
  secHeadAct1Click?: Types.Devlink.RuntimeProps;
  conSec1HeadAct1?: Types.Visibility.VisibilityConditions;
  conSec1HeadAct1Click?: Types.Devlink.RuntimeProps;
  conSec1Map?: Types.Devlink.Slot;
  conExampleCellMedia?: Types.Visibility.VisibilityConditions;
  exampleSec1VizSrc?: Types.Asset.Image;
  exampleSec1VizAlt?: Types.Basic.AltText;
  exampleSec1CaptLTxtSrc?: React.ReactNode;
  exampleSec1CaptRTxtSrc?: React.ReactNode;
  exampleSec1CellClick?: Types.Devlink.RuntimeProps;
  stat1Src?: React.ReactNode;
  stat2Src?: React.ReactNode;
  stat3Src?: React.ReactNode;
  emptyEmpty?: Types.Visibility.VisibilityConditions;
  emptyEmptyIcnSrc?: React.ReactNode;
  emptyEmptyHlineSrc?: React.ReactNode;
  emptyEmptySubTxtSrc?: React.ReactNode;
  emptyEmptyCtaTxtSrc?: React.ReactNode;
  emptyEmptyClick?: Types.Devlink.RuntimeProps;
  stat4Src?: React.ReactNode;
  stat2?: Types.Visibility.VisibilityConditions;
  stat3?: Types.Visibility.VisibilityConditions;
  stat4?: Types.Visibility.VisibilityConditions;
}): React.JSX.Element;
