import * as React from "react";
import * as Types from "./types";

declare function UploadCtrl(props: {
  as?: React.ElementType;
  upldDzIcn?: Types.Visibility.VisibilityConditions;
  upldDzAvtr?: Types.Visibility.VisibilityConditions;
  upldDzImg?: Types.Visibility.VisibilityConditions;
  upldDzIcnSrc?: React.ReactNode;
  upldDzIcnSz?: Types.Builtin.Text;
  upldDzImgSrc?: Types.Asset.Image;
  upldDzImgAlt?: Types.Basic.AltText;
  upldDzAvtrSrc?: Types.Asset.Image;
  upldDzAvtrAlt?: Types.Basic.AltText;
  upldDzTxtSrc?: React.ReactNode;
  upldDzChange?: Types.Builtin.Text;
  upldDzClick?: Types.Devlink.RuntimeProps;
  upldFileMap?: Types.Devlink.Slot;
  upldExampleFile?: Types.Visibility.VisibilityConditions;
  upldFileImgSrc?: Types.Asset.Image;
  upldFileImgAlt?: Types.Basic.AltText;
  upldFileCapt?: Types.Visibility.VisibilityConditions;
  upldFileTitleSrc?: React.ReactNode;
  upldFileClick?: Types.Devlink.RuntimeProps;
  optOptCamera?: Types.Visibility.VisibilityConditions;
  optOptLib?: Types.Visibility.VisibilityConditions;
  optOptUnsplash?: Types.Visibility.VisibilityConditions;
  optOptUrl?: Types.Visibility.VisibilityConditions;
  optUrlModal?: Types.Visibility.VisibilityConditions;
  optOptCameraClick?: Types.Devlink.RuntimeProps;
  optOptLibClick?: Types.Devlink.RuntimeProps;
  optOptUnsplashClick?: Types.Devlink.RuntimeProps;
  optOptUrlClick?: Types.Devlink.RuntimeProps;
  optUrlFldChange?: Types.Builtin.Text;
  optUrlFldClick?: Types.Devlink.RuntimeProps;
  optUrlGetClick?: Types.Devlink.RuntimeProps;
  optUrlCloseClick?: Types.Devlink.RuntimeProps;
  fileBar?: Types.Visibility.VisibilityConditions;
  upldOpt?: Types.Visibility.VisibilityConditions;
}): React.JSX.Element;
