# Cloudflare Pages configuration for Acrobi Design System
name = "acrobi-design-system"
compatibility_date = "2024-01-15"

# VitePress Documentation Site
[[pages_builds]]
name = "acrobi-docs"
build_command = "pnpm install && cd packages/ui && pnpm docs:build"
build_output_dir = "packages/ui/docs/.vitepress/dist"
environment_variables = { NODE_VERSION = "20" }

# Storybook Component Library
[[pages_builds]]  
name = "acrobi-storybook"
build_command = "pnpm install && cd packages/ui && pnpm build-storybook"
build_output_dir = "packages/ui/storybook-static"
environment_variables = { NODE_VERSION = "20" }