name: Deploy VitePress Docs

on:
  push:
    branches: [main]
    paths:
      - 'packages/ui/docs/**'
      - 'packages/ui/.vitepress/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

concurrency:
  group: deploy-docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-docs:
    name: Deploy VitePress to Cloudflare Pages
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.13.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build VitePress docs
        run: |
          echo "🏗️ Building VitePress documentation..."
          cd packages/ui
          pnpm docs:build
          echo "✅ VitePress build completed"

      - name: Prepare docs for deployment
        run: |
          echo "📦 Preparing docs for Cloudflare Pages deployment..."
          
          # Create deployment directory
          mkdir -p docs-dist
          
          # Copy VitePress build output
          cp -r packages/ui/docs/.vitepress/dist/* docs-dist/
          
          # Add custom domain configuration
          echo "docs.acrobi.com" > docs-dist/CNAME
          
          # Create robots.txt for public docs
          cat > docs-dist/robots.txt << EOF
          User-agent: *
          Allow: /
          
          Sitemap: https://docs.acrobi.com/sitemap.xml
          EOF
          
          # Create a basic sitemap
          cat > docs-dist/sitemap.xml << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
            <url>
              <loc>https://docs.acrobi.com/</loc>
              <changefreq>weekly</changefreq>
              <priority>1.0</priority>
            </url>
            <url>
              <loc>https://docs.acrobi.com/getting-started</loc>
              <changefreq>weekly</changefreq>
              <priority>0.9</priority>
            </url>
            <url>
              <loc>https://docs.acrobi.com/components/</loc>
              <changefreq>weekly</changefreq>
              <priority>0.8</priority>
            </url>
            <url>
              <loc>https://docs.acrobi.com/examples/</loc>
              <changefreq>monthly</changefreq>
              <priority>0.7</priority>
            </url>
          </urlset>
          EOF
          
          echo "✅ Documentation prepared for deployment"

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: acrobi-docs
          directory: docs-dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Update deployment status
        run: |
          echo "🚀 VitePress documentation deployed successfully!"
          echo "📖 Documentation URL: https://docs.acrobi.com"
          echo "🔍 Build artifacts:"
          ls -la docs-dist/

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ VitePress deployment failed!"
          echo "Please check the logs above for details."
          exit 1